[package]
name = "rerup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
regex = "1.8.4"
reqwest = "0.11.4"
tokio = {version="1.29.1" , features = ["full"]}
env = "0.0.0"
